name: publish dev

on:
  push:
    branches:
    - dev
    - dev-*

jobs:
  publish-dev:
    uses: fopina/scanner-go-entrypoint/build-workflow.yml@reusable_workflow
    with:
      tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
