name: publish dev

on:
  push:
    branches:
    - dev
    - dev-*

jobs:
  publish-dev:
    uses: fopina/scanner-go-entrypoint/.github/workflows/build-n-push.yml@reusable_workflow
    with:
      tags: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
