name: publish

on:
  push:
    branches:
    - main

jobs:
  publish:
    uses: fopina/scanner-go-entrypoint/.github/workflows/build-n-push.yml@v1
    with:
      tags: ghcr.io/${{ github.repository }}:${{ github.run_number }},ghcr.io/${{ github.repository }}:latest
